import { type NextPage } from "next";
import Head from "next/head";
import Todo from "../component/Todo";
import NewTodoForm from "../component/NewTodoForm";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data: todos = [] } = trpc.todo.getAll.useQuery();

  const todosList = todos.map((todo) => <Todo key={todo.id} todo={todo} />);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="TodoList">
        <h1>
          Todo List <span>A simple React Todo List App</span>
        </h1>
        <ul>{todosList}</ul>
        <NewTodoForm />
      </div>
    </>
  );
};

export default Home;
